### ISSUE TITLE
UA and RU translations

### ISSUE THREAD

**Issue by Eject37** [OwnGoalStudio/ColorfulWallpaperX#1]
Translated the tweak into these languages, thanks for making one of the most beautiful and useful tweaks for iOS.
My Havoc: `@Eject`

[Translations.zip](https://github.com/user-attachments/files/16885471/Translations.zip)

**Comment by Lessica** [comment]
[Merged](https://github.com/OwnGoalStudio/ColorfulWallpaperX/commit/056af2643888598813c6968fad349f550f40381c). Thank you.
